version: "3.7"
services:
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mycustom.cnf:/etc/my.cnf
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      testing_net:
          ipv4_address: 172.28.0.4
  web-server:
    image: amazonlinux:2
    depends_on:
      - mysql-server
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "80:80"
    networks:
      testing_net:
          ipv4_address: 172.28.0.3
    environment:
      WORDPRESS_DB_HOST: mysql-server
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5000:80"
    networks:
      testing_net:
          ipv4_address: 172.28.0.2
  ngrok:
    depends_on:
      - web-server
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      testing_net:
          ipv4_address: 172.28.0.5
volumes:
  mysql-data:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16